### ISSUE TITLE
9 laba

### ISSUE THREAD

**Issue by artlink52** [artlink52/coder_decoder#1]

**Comment by mackoel** [comment]
Артемий, почти все хорошо, есть вопрос:
- проверьте какие чанки возвращает file_reader и сколько их получится при разных буферах.

**Comment by artlink52** [comment]
FileReader возвращает chunks, которые являются блоками данных, прочитанными из файла. Каждый chunk представляет собой строку символов, прочитанных из файла, размером, определенным buffer_size. Все эти chunks затем собираются в список и возвращаются как результат работы метода read_file. Например, если файл имеет 100 символов, и buffer_size равен 10, то при чтении файла метод read_file вернет список из 10 chunks, каждый размером в 10 символов. Если buffer_size изменить на 20, то вернется список из 5 chunks, каждый размером в 20 символов.

**Comment by mackoel** [comment]
Артемий, эту теорию я понял, но Вы проверили, что Ваш код делает, например чанки эти печатали там, где они приходят из file reader?

**Comment by artlink52** [comment]
![qwe](https://github.com/artlink52/coder_decoder/assets/118747024/155069ab-c6ae-4fb3-aa15-eeed7271d64f)
Вот chunks при buffer_size = 10 - их 5 штук

**Comment by artlink52** [comment]
![qwe1](https://github.com/artlink52/coder_decoder/assets/118747024/3e3ccb9e-2cf9-40ad-9ec6-4e689c2e6910)
При buffer_size = 5 - 10 штук

**Comment by mackoel** [comment]
Артемий, да, это хорошо, наверно я не точно вопрос задал. Проблема в том, что у Вас в file reader в списке chunks накапливается постепенно весь файл, что потенциально мы хотим избежать, иначе бы считали его целиком.

**Comment by mackoel** [comment]
Артемий, зачел, за курс хорошо, но имейте в виду, что в result у Вас все равно идет накопление и память может занять.
